services:
  node:
    container_name: node
    build:
      dockerfile: ./deployments/docker/Dockerfile.golang.local
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
        ID: 1
