FROM golang:1.24-alpine3.21 AS builder
ARG CGO_ENABLED=0
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build

FROM scratch
COPY --from=builder /app/distributed-key-value-store /distributed-key-value-store
ENTRYPOINT ["/distributed-key-value-store"]
