# @name Put a value

POST {{url}}/values
Content-Type: application/json

{
    "key": "something",
    "value": "anything"
}

###

# @name Get a value

GET {{url}}/values/something

###

# @name Delete a key, value pair

DELETE {{url}}/values/something

###

# @name Get raft status

GET {{url}}/status

###
